<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>DTAM</AssemblyName>
    <RootNamespace>DTAM.Client</RootNamespace>
    <Version>3.0.2</Version>
    <FileVersion>3.0.2.0</FileVersion>
    <AssemblyVersion>3.0.2.0</AssemblyVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>
</Project>
