const MAX_PLAYERS = 15;
const MIN_PLAYERS = 2;
const MAP_SIZE = 150;
const PLAYER_RADIUS = 0.32;
const RECONNECT_GRACE_MS = 30000;
const START_KILL_COOLDOWN_MS = 10000;
const POST_MEETING_KILL_COOLDOWN_MS = 8000;
const RESULT_MS = 3000;
const DOOR_LOCK_MS = 10000;
const MAX_WS_MESSAGE_BYTES = 16 * 1024;
const EMERGENCY_STATION = 'console-c1';
const COLORS = ['#ef4444','#f97316','#eab308','#84cc16','#22c55e','#10b981','#14b8a6','#06b6d4','#3b82f6','#6366f1','#8b5cf6','#a855f7','#d946ef','#f43f5e','#ec4899'];
const OBJECT_DEFS = [
  { id:'power-nw', x:7.5, y:7.5, label:'西北配电箱' },
  { id:'relay-n', x:42.5, y:7.5, label:'北区中继器' },
  { id:'sensor-ne', x:92.5, y:7.5, label:'东北传感器' },
  { id:'gate-e', x:142.5, y:32.5, label:'东侧门禁' },
  { id:'pump-w', x:7.5, y:57.5, label:'西区水泵' },
  { id:'console-c1', x:67.5, y:57.5, label:'中央控制台 A' },
  { id:'console-c2', x:82.5, y:92.5, label:'中央控制台 B' },
  { id:'radio-e', x:142.5, y:82.5, label:'东区无线电' },
  { id:'beacon-sw', x:17.5, y:117.5, label:'西南信标' },
  { id:'panel-s', x:67.5, y:142.5, label:'南区面板' },
  { id:'relay-se', x:117.5, y:142.5, label:'东南中继器' },
  { id:'gate-s', x:142.5, y:117.5, label:'南侧门禁' }
];
const TASK_IDS = OBJECT_DEFS.filter(o => o.id !== EMERGENCY_STATION).map(o => o.id);
const TASK_TYPES = {
  'power-nw':'hold','relay-n':'sequence','sensor-ne':'keypad','gate-e':'align','pump-w':'hold',
  'console-c2':'sequence','radio-e':'keypad','beacon-sw':'align','panel-s':'hold','relay-se':'sequence','gate-s':'keypad'
};
const DOOR_CELLS=[[75,56],[75,57],[75,58],[75,91],[75,92],[75,93],[66,75],[67,75],[68,75],[81,75],[82,75],[83,75]];
const DOOR_CELL_SET=new Set(DOOR_CELLS.map(([x,y])=>`${x},${y}`));
const VISUAL_TASK_IDS=new Set(['beacon-sw','panel-s']);
const VENT_DEFS = [
  {id:'vent-nw',x:30.5,y:30.5,links:['vent-n','vent-ne']},
  {id:'vent-n',x:69.5,y:31.5,links:['vent-nw','vent-ne']},
  {id:'vent-ne',x:112.5,y:32.5,links:['vent-nw','vent-n']},
  {id:'vent-sw',x:20.5,y:92.5,links:['vent-c','vent-se']},
  {id:'vent-c',x:75.5,y:112.5,links:['vent-sw','vent-se']},
  {id:'vent-se',x:130.5,y:92.5,links:['vent-sw','vent-c']}
];
const SABOTAGE_DEFS = {
  lights:{label:'断电',durationMs:0,stations:['power-nw']},
  reactor:{label:'反应堆熔毁',durationMs:35000,stations:['relay-n','relay-se']},
  o2:{label:'O₂ 耗尽',durationMs:30000,stations:['sensor-ne','pump-w']}
};
const DEFAULT_SETTINGS = Object.freeze({
  impostors:1,tasksPerCrew:4,moveSpeed:4.6,killCooldown:20,discussion:12,voting:30,
  emergencyMeetings:1,sabotageCooldown:20,confirmEjects:true
});
const SPAWNS = [[75.5,75.5],[73.5,75.5],[77.5,75.5],[75.5,73.5],[75.5,77.5],[72.5,72.5],[78.5,72.5],[72.5,78.5],[78.5,78.5],[74,72],[76,72],[72,74],[78,74],[72,76],[78,76]];

const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
const clampInt=(v,min,max,fb)=>Math.round(clamp(Number.isFinite(Number(v))?Number(v):fb,min,max));
function sanitizeName(value){const text=String(value??'').replace(/[\u0000-\u001f\u007f]/g,'').trim();return(text||'玩家').slice(0,12);}
function sanitizeText(value){return String(value??'').replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/g,'').trim().slice(0,100);}
function jsonSend(ws,data){try{ws.send(JSON.stringify(data));return true;}catch(_){return false;}}
function shuffled(input){const a=[...input],buf=new Uint32Array(Math.max(1,a.length));crypto.getRandomValues(buf);for(let i=a.length-1;i>0;i--){const j=buf[i%buf.length]%(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;}
function randomInt(min,max){const b=new Uint32Array(1);crypto.getRandomValues(b);return min+(b[0]%(max-min+1));}
function normalizeSettings(raw={},base=DEFAULT_SETTINGS){return{
  impostors:clampInt(raw.impostors,1,3,base.impostors),
  tasksPerCrew:clampInt(raw.tasksPerCrew,2,6,base.tasksPerCrew),
  moveSpeed:Math.round(clamp(Number(raw.moveSpeed)||base.moveSpeed,3.5,6)*10)/10,
  killCooldown:clampInt(raw.killCooldown,10,45,base.killCooldown),
  discussion:clampInt(raw.discussion,0,30,base.discussion),
  voting:clampInt(raw.voting,15,90,base.voting),
  emergencyMeetings:clampInt(raw.emergencyMeetings,0,3,base.emergencyMeetings),
  sabotageCooldown:clampInt(raw.sabotageCooldown,10,45,base.sabotageCooldown),
  confirmEjects:typeof raw.confirmEjects==='boolean'?raw.confirmEjects:!!base.confirmEjects
};}
function buildMap(){const map=new Uint8Array(MAP_SIZE*MAP_SIZE),setWall=(x,y,v=1)=>{if(x>=0&&x<MAP_SIZE&&y>=0&&y<MAP_SIZE)map[y*MAP_SIZE+x]=v;};for(let i=0;i<MAP_SIZE;i++){setWall(i,0);setWall(i,MAP_SIZE-1);setWall(0,i);setWall(MAP_SIZE-1,i);}const lines=[25,50,75,100,125];lines.forEach((x,li)=>{for(let y=1;y<MAP_SIZE-1;y++){const sector=Math.floor(y/25),local=y%25,ds=((sector+li)%2===0)?6:16;if(local<ds||local>ds+2)setWall(x,y);}});lines.forEach((y,li)=>{for(let x=1;x<MAP_SIZE-1;x++){const sector=Math.floor(x/25),local=x%25,ds=((sector+li+1)%2===0)?6:16;if(local<ds||local>ds+2)setWall(x,y);}});for(let sy=0;sy<6;sy++)for(let sx=0;sx<6;sx++){if(sx===3&&sy===3)continue;if((sx+sy)%2!==0)continue;const cx=sx*25+13,cy=sy*25+13,h=((sx*3+sy)%2)===0,w=h?5:2,hh=h?2:5;for(let oy=-Math.floor(hh/2);oy<=Math.floor(hh/2);oy++)for(let ox=-Math.floor(w/2);ox<=Math.floor(w/2);ox++)setWall(cx+ox,cy+oy);}for(let y=70;y<=80;y++)for(let x=70;x<=80;x++)setWall(x,y,0);for(const o of [...OBJECT_DEFS,...VENT_DEFS]){const cx=Math.floor(o.x),cy=Math.floor(o.y);for(let y=cy-1;y<=cy+1;y++)for(let x=cx-1;x<=cx+1;x++)setWall(x,y,0);}return map;}
const MAP_DATA=buildMap();
function isWallCell(c,r){if(c<0||r<0||c>=MAP_SIZE||r>=MAP_SIZE)return true;return MAP_DATA[r*MAP_SIZE+c]===1;}
function isDoorCell(c,r){return DOOR_CELL_SET.has(`${c},${r}`);}
export function circleHitsWall(x,y,r=PLAYER_RADIUS,doorsClosed=false){const minX=Math.floor(x-r),maxX=Math.floor(x+r),minY=Math.floor(y-r),maxY=Math.floor(y+r);for(let row=minY;row<=maxY;row++)for(let col=minX;col<=maxX;col++){if(!isWallCell(col,row)&&!(doorsClosed&&isDoorCell(col,row)))continue;const nx=clamp(x,col,col+1),ny=clamp(y,row,row+1),dx=x-nx,dy=y-ny;if(dx*dx+dy*dy<r*r)return true;}return false;}
export function pathHitsWall(from,to,r=PLAYER_RADIUS,doorsClosed=false){const distance=Math.hypot(to.x-from.x,to.y-from.y),steps=Math.max(1,Math.ceil(distance/Math.max(.08,r/2)));for(let i=1;i<=steps;i++){const t=i/steps;if(circleHitsWall(from.x+(to.x-from.x)*t,from.y+(to.y-from.y)*t,r,doorsClosed))return true;}return false;}
function hasLineOfSight(a,b,doorsClosed=false){const d=Math.hypot(b.x-a.x,b.y-a.y),steps=Math.max(1,Math.ceil(d/0.12));for(let i=1;i<steps;i++){const t=i/steps,x=a.x+(b.x-a.x)*t,y=a.y+(b.y-a.y)*t,c=Math.floor(x),r=Math.floor(y);if(isWallCell(c,r)||(doorsClosed&&isDoorCell(c,r)))return false;}return true;}
function publicMeeting(meeting,myId=''){if(!meeting)return null;return{id:meeting.id,stage:meeting.stage,reasonText:meeting.reasonText,callerId:meeting.callerId,bodyId:meeting.bodyId||'',discussionEndsAt:meeting.discussionEndsAt,votingEndsAt:meeting.votingEndsAt,resumeAt:meeting.resumeAt||0,myVote:meeting.votes?.[myId]||''};}
function publicSabotage(s){if(!s)return null;const d=SABOTAGE_DEFS[s.type];return{type:s.type,label:d?.label||s.type,startedAt:s.startedAt,endsAt:s.endsAt||0,fixedStations:Array.isArray(s.fixedStations)?s.fixedStations:[],requiredStations:d?.stations||[]};}

export class GameRoom {
  constructor(ctx,env){this.ctx=ctx;this.env=env;this.initialized=false;this.createdAt=0;this.hostId='';this.players={};this.bodies=[];this.phase='lobby';this.startedAt=0;this.endedAt=0;this.winner='';this.reason='';this.meeting=null;this.settings={...DEFAULT_SETTINGS};this.sabotage=null;this.sabotageReadyAt=0;this.doorLockUntil=0;this.persistTimer=null;ctx.blockConcurrencyWhile(async()=>{const s=await ctx.storage.get('snapshot');if(s)this.restore(s);this.reconcileSockets();});}
  restore(s){this.initialized=!!s.initialized;this.createdAt=Number(s.createdAt||0);this.hostId=String(s.hostId||'');this.players=s.players||{};this.bodies=Array.isArray(s.bodies)?s.bodies:[];this.phase=s.phase||'lobby';this.startedAt=Number(s.startedAt||0);this.endedAt=Number(s.endedAt||0);this.winner=s.winner||'';this.reason=s.reason||'';this.meeting=s.meeting||null;this.settings=normalizeSettings(s.settings||{},DEFAULT_SETTINGS);this.sabotage=s.sabotage||null;this.sabotageReadyAt=Number(s.sabotageReadyAt||0);this.doorLockUntil=Number(s.doorLockUntil||0);for(const p of Object.values(this.players)){p.completed=Array.isArray(p.completed)?p.completed:[];p.tasks=Array.isArray(p.tasks)?p.tasks:[];p.fakeTasks=Array.isArray(p.fakeTasks)?p.fakeTasks:[];p.alive=p.alive!==false;p.connected=false;p.connectionId='';p.inVent=!!p.inVent;p.ventId=String(p.ventId||'');p.activeTask=null;}}
  reconcileSockets(){const live=new Map();for(const ws of this.ctx.getWebSockets()){const a=ws.deserializeAttachment();if(a?.playerId)live.set(a.playerId,a.connectionId||'');}for(const p of Object.values(this.players)){if(live.has(p.id)){p.connected=true;p.connectionId=live.get(p.id);}}}
  snapshot(){return{initialized:this.initialized,createdAt:this.createdAt,hostId:this.hostId,players:this.players,bodies:this.bodies,phase:this.phase,startedAt:this.startedAt,endedAt:this.endedAt,winner:this.winner,reason:this.reason,meeting:this.meeting,settings:this.settings,sabotage:this.sabotage,sabotageReadyAt:this.sabotageReadyAt,doorLockUntil:this.doorLockUntil};}
  async persistNow(){await this.ctx.storage.put('snapshot',this.snapshot());}
  schedulePersist(){if(this.persistTimer)return;this.persistTimer=setTimeout(async()=>{this.persistTimer=null;try{await this.persistNow();}catch(_){}},1200);}
  publicPlayers(){return Object.values(this.players).map(p=>({id:p.id,name:p.name,color:p.color,pos:p.pos,isHost:p.id===this.hostId,connected:!!p.connected,alive:p.alive!==false,inVent:!!p.inVent}));}
  taskProgress(){let total=0,done=0;for(const p of Object.values(this.players)){if(p.role!=='crewmate')continue;total+=p.tasks.length;done+=p.completed.length;}return{taskDone:done,taskTotal:total};}
  selfState(player){return{role:player?.role||'',alive:player?.alive!==false,tasks:Array.isArray(player?.tasks)?player.tasks:[],completed:Array.isArray(player?.completed)?player.completed:[],fakeTasks:Array.isArray(player?.fakeTasks)?player.fakeTasks:[],killReadyAt:Number(player?.killReadyAt||0),sabotageReadyAt:player?.role==='impostor'?Number(this.sabotageReadyAt||0):0,emergencyUsed:Number(player?.emergencyUsed||0),inVent:!!player?.inVent,ventId:String(player?.ventId||'')};}
  publicGame(myId=''){const t=this.taskProgress();return{phase:this.phase,winner:this.winner,reason:this.reason,taskDone:t.taskDone,taskTotal:t.taskTotal,meeting:publicMeeting(this.meeting,myId),settings:this.settings,sabotage:publicSabotage(this.sabotage),doorLockUntil:Number(this.doorLockUntil||0)};}
  socketForPlayer(id){for(const ws of this.ctx.getWebSockets()){const a=ws.deserializeAttachment();const p=this.players[id];if(a?.playerId===id&&(!p?.connectionId||!a.connectionId||a.connectionId===p.connectionId))return ws;}return null;}
  sendTo(id,data){const ws=this.socketForPlayer(id);if(ws)jsonSend(ws,data);}
  broadcast(data,exceptId=''){for(const ws of this.ctx.getWebSockets()){const a=ws.deserializeAttachment();if(exceptId&&a?.playerId===exceptId)continue;jsonSend(ws,data);}}
  sendStateTo(ws){const a=ws.deserializeAttachment(),p=a?.playerId?this.players[a.playerId]:null;if(!p)return;jsonSend(ws,{t:'state',players:this.publicPlayers(),bodies:this.bodies,game:this.publicGame(p.id),selfState:this.selfState(p)});}
  broadcastState(){for(const ws of this.ctx.getWebSockets())this.sendStateTo(ws);}
  nextColor(){const used=new Set(Object.values(this.players).map(p=>p.color));return COLORS.find(c=>!used.has(c))||COLORS[Object.keys(this.players).length%COLORS.length];}
  spawnForIndex(i){const [x,y]=SPAWNS[i%SPAWNS.length];return{x,y};}
  electHost(){const a=Object.values(this.players).filter(p=>p.connected).sort((x,y)=>x.joinedAt-y.joinedAt);this.hostId=a[0]?.id||Object.values(this.players).sort((x,y)=>x.joinedAt-y.joinedAt)[0]?.id||'';}
  sendError(ws,code,message,close=true){jsonSend(ws,{t:'error',code,message});if(close)try{ws.close(4000,code);}catch(_){} }
  async scheduleNextAlarm(){let next=0;const now=Date.now();if(this.meeting){if(this.meeting.stage==='voting')next=this.meeting.votingEndsAt;else if(this.meeting.stage==='result')next=this.meeting.resumeAt;}if(this.phase==='playing'&&this.sabotage?.endsAt){const t=Number(this.sabotage.endsAt);if(t>now&&(next===0||t<next))next=t;}if(this.phase==='playing'&&this.doorLockUntil>now&&(next===0||this.doorLockUntil<next))next=this.doorLockUntil;for(const p of Object.values(this.players)){if(!p.connected&&p.lastSeen){const t=Number(p.lastSeen)+RECONNECT_GRACE_MS;if(t>now&&(next===0||t<next))next=t;}}if(next>0)await this.ctx.storage.setAlarm(Math.max(now+100,next));else await this.ctx.storage.deleteAlarm();}
  cleanupExpired(now=Date.now()){let changed=false;for(const p of Object.values({...this.players})){if(!p.connected&&now-Number(p.lastSeen||now)>RECONNECT_GRACE_MS){delete this.players[p.id];changed=true;}}if(changed){if(!this.players[this.hostId])this.electHost();this.bodies=this.bodies.filter(b=>this.players[b.playerId]);}return changed;}
  async removePlayer(id,announce=false){const p=this.players[id];if(!p)return;delete this.players[id];this.bodies=this.bodies.filter(b=>b.playerId!==id);if(this.hostId===id)this.electHost();if(announce)this.broadcast({t:'notice',text:`${p.name} 离开了房间`});await this.persistNow();this.broadcastState();await this.checkWin('leave');await this.scheduleNextAlarm();}

  async fetch(request){const url=new URL(request.url);if((request.headers.get('Upgrade')||'').toLowerCase()!=='websocket')return new Response('WebSocket required',{status:426});const room=url.searchParams.get('room')||'',create=url.searchParams.get('create')==='1',name=sanitizeName(url.searchParams.get('name')),token=String(url.searchParams.get('token')||'');const pair=new WebSocketPair(),client=pair[0],server=pair[1];this.ctx.acceptWebSocket(server);if(!/^\d{6}$/.test(room)){this.sendError(server,'bad_room','房间号格式错误');return new Response(null,{status:101,webSocket:client});}
    const now=Date.now();this.cleanupExpired(now);let player=token?Object.values(this.players).find(p=>p.token===token):null,resumed=false;const connectionId=crypto.randomUUID();
    if(player){if(now-Number(player.lastSeen||now)<=RECONNECT_GRACE_MS||player.connected){const old=this.socketForPlayer(player.id);if(old)try{old.close(4002,'replaced');}catch(_){}resumed=true;}else{delete this.players[player.id];player=null;}}
    if(!player){if(create&&this.initialized&&Object.keys(this.players).length){this.sendError(server,'room_exists','房间号已存在');return new Response(null,{status:101,webSocket:client});}if(!create&&!this.initialized){this.sendError(server,'room_not_found','房间不存在');return new Response(null,{status:101,webSocket:client});}if(this.phase!=='lobby'){this.sendError(server,'game_in_progress','游戏已经开始，只能用原会话重连');return new Response(null,{status:101,webSocket:client});}if(Object.keys(this.players).length>=MAX_PLAYERS){this.sendError(server,'room_full','房间已满');return new Response(null,{status:101,webSocket:client});}if(create&&!this.initialized){this.initialized=true;this.createdAt=now;}const id=crypto.randomUUID();player={id,token:crypto.randomUUID(),name,color:this.nextColor(),pos:this.spawnForIndex(Object.keys(this.players).length),connected:true,connectionId,joinedAt:now,lastSeen:now,lastMoveAt:now,lastChatAt:0,role:'',alive:true,tasks:[],completed:[],killReadyAt:0,emergencyUsed:0,inVent:false,ventId:'',activeTask:null};this.players[id]=player;if(!this.hostId)this.hostId=id;}
    player.connected=true;player.connectionId=connectionId;player.lastSeen=now;server.serializeAttachment({playerId:player.id,token:player.token,connectionId});await this.persistNow();jsonSend(server,{t:'welcome',room,resumed,self:{id:player.id,token:player.token},hostId:this.hostId,players:this.publicPlayers(),bodies:this.bodies,game:this.publicGame(player.id),selfState:this.selfState(player)});if(!resumed)this.broadcast({t:'notice',text:`${player.name} 加入了房间`},player.id);this.broadcastState();await this.scheduleNextAlarm();return new Response(null,{status:101,webSocket:client});}

  async webSocketMessage(ws,message){const a=ws.deserializeAttachment(),player=a?.playerId?this.players[a.playerId]:null;if(!player||(a?.connectionId&&player.connectionId!==a.connectionId)){this.sendError(ws,'session_invalid','会话已失效');return;}player.connected=true;player.lastSeen=Date.now();const bytes=typeof message==='string'?new TextEncoder().encode(message).byteLength:message.byteLength;if(bytes>MAX_WS_MESSAGE_BYTES){this.sendError(ws,'message_too_large','消息过大');return;}let msg;try{msg=JSON.parse(typeof message==='string'?message:new TextDecoder('utf-8',{fatal:true}).decode(message));}catch(_){return;}if(!msg||typeof msg.t!=='string')return;
    if(msg.t==='ping'){jsonSend(ws,{t:'pong',at:Date.now()});return;}
    if(msg.t==='chat'){const text=sanitizeText(msg.text),now=Date.now();if(!text)return;if(this.phase==='playing')return;if(now-Number(player.lastChatAt||0)<300)return;player.lastChatAt=now;this.broadcast({t:'chat',name:player.name,text,at:now});return;}
    if(msg.t==='pos'){if(this.phase!=='playing'||player.inVent)return;const x=Number(msg.x),y=Number(msg.y),now=Date.now();if(!Number.isFinite(x)||!Number.isFinite(y))return;if(x<PLAYER_RADIUS||y<PLAYER_RADIUS||x>MAP_SIZE-PLAYER_RADIUS||y>MAP_SIZE-PLAYER_RADIUS){jsonSend(ws,{t:'correct',x:player.pos.x,y:player.pos.y});return;}const target={x,y};if(player.alive&&pathHitsWall(player.pos,target,PLAYER_RADIUS,this.doorLockUntil>now)){jsonSend(ws,{t:'correct',x:player.pos.x,y:player.pos.y});return;}const dt=clamp((now-Number(player.lastMoveAt||now))/1000,.016,.35),maxDist=this.settings.moveSpeed*dt+.7;if(Math.hypot(x-player.pos.x,y-player.pos.y)>maxDist){jsonSend(ws,{t:'correct',x:player.pos.x,y:player.pos.y});return;}player.pos=target;player.lastMoveAt=now;this.broadcast({t:'pos',id:player.id,x,y,alive:player.alive,inVent:false},player.id);this.schedulePersist();return;}
    if(msg.t==='kick'){if(player.id!==this.hostId||this.phase!=='lobby')return;const id=String(msg.id||'');if(!id||id===player.id||!this.players[id])return;const target=this.players[id],targetWs=this.socketForPlayer(id);if(targetWs)jsonSend(targetWs,{t:'kicked'});delete this.players[id];if(targetWs)try{targetWs.close(4003,'kicked');}catch(_){}await this.persistNow();this.broadcast({t:'notice',text:`${target.name} 被移出了房间`});this.broadcastState();return;}
    if(msg.t==='settings'){await this.updateSettings(player,msg.settings||{},ws);return;}
    if(msg.t==='start'){await this.startGame(player);return;}
    if(msg.t==='task_begin'){await this.beginTask(player,String(msg.id||''),ws);return;}
    if(msg.t==='task_complete'){await this.finishTask(player,msg,ws);return;}
    if(msg.t==='task'){this.sendError(ws,'legacy_task_disabled','请刷新页面后重试任务');return;}
    if(msg.t==='kill'){await this.killPlayer(player,String(msg.targetId||''),ws);return;}
    if(msg.t==='report'){await this.reportBody(player,String(msg.bodyId||''));return;}
    if(msg.t==='emergency'){await this.callEmergency(player,ws);return;}
    if(msg.t==='vote'){await this.castVote(player,String(msg.target||''));return;}
    if(msg.t==='sabotage'){await this.startSabotage(player,String(msg.kind||''),ws);return;}
    if(msg.t==='sabotage_fix'){await this.fixSabotage(player,String(msg.stationId||''),ws);return;}
    if(msg.t==='vent'){await this.handleVent(player,String(msg.action||''),String(msg.ventId||''),ws);return;}
    if(msg.t==='reset'){await this.resetLobby(player);return;}
    if(msg.t==='leave'){await this.removePlayer(player.id,true);try{ws.close(1000,'leave');}catch(_){}return;}
  }

  async updateSettings(player,raw,ws){if(player.id!==this.hostId||this.phase!=='lobby')return;this.settings=normalizeSettings(raw,this.settings);await this.persistNow();this.broadcastState();jsonSend(ws,{t:'settings_ok',settings:this.settings});}
  async startGame(player){if(player.id!==this.hostId||this.phase!=='lobby')return;const active=Object.values(this.players).filter(p=>p.connected);if(active.length<MIN_PLAYERS){this.sendTo(player.id,{t:'error',code:'not_enough_players',message:`至少需要 ${MIN_PLAYERS} 名玩家`});return;}const now=Date.now(),order=shuffled(active),maxImp=Math.max(1,Math.floor((active.length-1)/2)),impCount=Math.min(this.settings.impostors,maxImp),impIds=new Set(order.slice(0,impCount).map(p=>p.id));this.bodies=[];this.phase='playing';this.startedAt=now;this.endedAt=0;this.winner='';this.reason='';this.meeting=null;this.sabotage=null;this.doorLockUntil=0;this.sabotageReadyAt=now+10000;active.forEach((p,i)=>{p.role=impIds.has(p.id)?'impostor':'crewmate';p.alive=true;p.completed=[];p.tasks=p.role==='crewmate'?shuffled(TASK_IDS).slice(0,this.settings.tasksPerCrew):[];p.fakeTasks=p.role==='impostor'?shuffled(TASK_IDS).slice(0,this.settings.tasksPerCrew):[];p.killReadyAt=p.role==='impostor'?now+Math.min(START_KILL_COOLDOWN_MS,this.settings.killCooldown*1000):0;p.emergencyUsed=0;p.pos=this.spawnForIndex(i);p.lastMoveAt=now;p.inVent=false;p.ventId='';p.activeTask=null;});await this.persistNow();for(const p of active)this.sendTo(p.id,{t:'game_start',game:this.publicGame(p.id),selfState:this.selfState(p)});this.broadcastState();this.broadcast({t:'notice',text:'游戏开始'});await this.scheduleNextAlarm();}
  createTaskChallenge(id){const type=TASK_TYPES[id]||'hold',token=crypto.randomUUID(),now=Date.now();if(type==='sequence'){const seq=shuffled([0,1,2,3]);return{token,type,answer:seq.join(','),minCompleteAt:now+500,payload:{sequence:seq}};}if(type==='keypad'){const code=String(randomInt(1000,9999));return{token,type,answer:code,minCompleteAt:now+600,payload:{code}};}if(type==='align'){const target=randomInt(18,82);return{token,type,answer:String(target),minCompleteAt:now+500,payload:{target}};}return{token,type:'hold',answer:'ok',minCompleteAt:now+1200,payload:{duration:1200}};}
  async beginTask(player,id,ws){if(this.phase!=='playing'||player.role!=='crewmate'||!player.tasks.includes(id)||player.completed.includes(id)||player.inVent)return;const def=OBJECT_DEFS.find(o=>o.id===id);if(!def||Math.hypot(player.pos.x-def.x,player.pos.y-def.y)>1.65)return;const c=this.createTaskChallenge(id);player.activeTask={id,...c,startedAt:Date.now()};jsonSend(ws,{t:'task_challenge',id,token:c.token,type:c.type,payload:c.payload,label:def.label});this.schedulePersist();}
  async finishTask(player,msg,ws){const id=String(msg.id||''),token=String(msg.token||''),c=player.activeTask;if(this.phase!=='playing'||player.role!=='crewmate'||!c||c.id!==id||c.token!==token)return;if(Date.now()<Number(c.minCompleteAt||0)){jsonSend(ws,{t:'task_fail',message:'操作太快，请再试'});return;}const def=OBJECT_DEFS.find(o=>o.id===id);if(!def||Math.hypot(player.pos.x-def.x,player.pos.y-def.y)>1.75)return;const answer=String(msg.answer??'');let ok=false;if(c.type==='hold')ok=true;else if(c.type==='align')ok=Math.abs(Number(answer)-Number(c.answer))<=4;else ok=answer===String(c.answer);if(!ok){jsonSend(ws,{t:'task_fail',message:'任务操作不正确'});return;}player.activeTask=null;if(!player.completed.includes(id))player.completed.push(id);const t=this.taskProgress();jsonSend(ws,{t:'task_done',completed:player.completed,taskDone:t.taskDone,taskTotal:t.taskTotal});this.broadcast({t:'task_progress',taskDone:t.taskDone,taskTotal:t.taskTotal},player.id);if(VISUAL_TASK_IDS.has(id))this.broadcast({t:'visual_task',stationId:id,playerId:player.id,until:Date.now()+1600});await this.persistNow();await this.checkWin('tasks');}
  async killPlayer(killer,targetId,ws){if(this.phase!=='playing'||killer.role!=='impostor'||!killer.alive||killer.inVent)return;const now=Date.now();if(now<Number(killer.killReadyAt||0)){jsonSend(ws,{t:'error',code:'kill_cooldown',message:'击杀冷却中'});return;}const target=this.players[targetId];if(!target||!target.connected||!target.alive||target.inVent||target.id===killer.id)return;if(Math.hypot(killer.pos.x-target.pos.x,killer.pos.y-target.pos.y)>1.2||!hasLineOfSight(killer.pos,target.pos,this.doorLockUntil>Date.now()))return;target.alive=false;target.inVent=false;target.ventId='';this.bodies.push({id:crypto.randomUUID(),playerId:target.id,name:target.name,color:target.color,x:target.pos.x,y:target.pos.y,createdAt:now});killer.killReadyAt=now+this.settings.killCooldown*1000;this.sendTo(target.id,{t:'killed'});jsonSend(ws,{t:'kill_ok',killReadyAt:killer.killReadyAt});this.broadcast({t:'bodies',bodies:this.bodies});this.broadcastState();await this.persistNow();await this.checkWin('kill');}
  async reportBody(player,bodyId){if(this.phase!=='playing'||!player.alive||player.inVent)return;const body=this.bodies.find(b=>b.id===bodyId);if(!body||Math.hypot(player.pos.x-body.x,player.pos.y-body.y)>1.7)return;await this.startMeeting(player,{bodyId:body.id,reasonText:`${player.name} 报告了 ${body.name} 的尸体`});}
  async callEmergency(player,ws){if(this.phase!=='playing'||!player.alive||player.inVent||Number(player.emergencyUsed||0)>=this.settings.emergencyMeetings)return;if(this.sabotage){jsonSend(ws,{t:'error',code:'sabotage_active',message:'破坏期间不能召开紧急会议'});return;}const s=OBJECT_DEFS.find(o=>o.id===EMERGENCY_STATION);if(!s||Math.hypot(player.pos.x-s.x,player.pos.y-s.y)>1.6)return;player.emergencyUsed=Number(player.emergencyUsed||0)+1;await this.startMeeting(player,{bodyId:'',reasonText:`${player.name} 召开了紧急会议`});}
  async startMeeting(player,{bodyId='',reasonText=''}){const now=Date.now();this.phase='meeting';this.sabotage=null;this.doorLockUntil=0;this.sabotageReadyAt=now+this.settings.sabotageCooldown*1000;for(const p of Object.values(this.players)){p.inVent=false;p.ventId='';}this.meeting={id:crypto.randomUUID(),stage:'voting',callerId:player.id,bodyId,reasonText,discussionEndsAt:now+this.settings.discussion*1000,votingEndsAt:now+(this.settings.discussion+this.settings.voting)*1000,votes:{},resumeAt:0};await this.persistNow();for(const p of Object.values(this.players))this.sendTo(p.id,{t:'meeting',meeting:publicMeeting(this.meeting,p.id)});this.broadcastState();await this.scheduleNextAlarm();}
  async castVote(player,target){if(this.phase!=='meeting'||!this.meeting||this.meeting.stage!=='voting'||!player.alive)return;const now=Date.now();if(now<this.meeting.discussionEndsAt||now>=this.meeting.votingEndsAt)return;if(this.meeting.votes[player.id])return;if(target!=='skip'&&(!this.players[target]||!this.players[target].alive))return;this.meeting.votes[player.id]=target;await this.persistNow();for(const p of Object.values(this.players))this.sendTo(p.id,{t:'meeting',meeting:publicMeeting(this.meeting,p.id)});const voters=Object.values(this.players).filter(p=>p.alive&&p.connected);if(voters.length&&voters.every(p=>this.meeting.votes[p.id]))await this.resolveMeeting();}
  async resolveMeeting(){if(this.phase!=='meeting'||!this.meeting||this.meeting.stage!=='voting')return;const counts=new Map();for(const target of Object.values(this.meeting.votes||{}))counts.set(target,(counts.get(target)||0)+1);let top=0,winners=[];for(const [id,n] of counts){if(id==='skip')continue;if(n>top){top=n;winners=[id];}else if(n===top&&n>0)winners.push(id);}const skip=counts.get('skip')||0;let ejected=null;if(winners.length===1&&top>skip)ejected=this.players[winners[0]]||null;if(ejected)ejected.alive=false;let text='无人被放逐。';if(ejected)text=this.settings.confirmEjects?`${ejected.name} 被放逐了。${ejected.role==='impostor'?'TA 是内鬼。':'TA 不是内鬼。'}`:`${ejected.name} 被放逐了。`;this.meeting.stage='result';this.meeting.resumeAt=Date.now()+RESULT_MS;this.broadcast({t:'meeting_result',text});await this.persistNow();const won=await this.checkWin('vote');if(won)return;await this.scheduleNextAlarm();}
  async resumeAfterMeeting(){if(this.phase!=='meeting'||!this.meeting||this.meeting.stage!=='result')return;const now=Date.now();this.phase='playing';this.meeting=null;this.bodies=[];let i=0;for(const p of Object.values(this.players)){p.pos=this.spawnForIndex(i++);p.lastMoveAt=now;p.inVent=false;p.ventId='';if(p.role==='impostor'&&p.alive)p.killReadyAt=now+Math.min(POST_MEETING_KILL_COOLDOWN_MS,this.settings.killCooldown*1000);}await this.persistNow();for(const p of Object.values(this.players))this.sendTo(p.id,{t:'resume_play',players:this.publicPlayers(),selfState:this.selfState(p)});this.broadcastState();await this.scheduleNextAlarm();}

  async startSabotage(player,kind,ws){if(this.phase!=='playing'||player.role!=='impostor'||!player.alive||player.inVent)return;const now=Date.now();if(now<this.sabotageReadyAt){jsonSend(ws,{t:'error',code:'sabotage_cooldown',message:'破坏冷却中'});return;}if(kind==='doors'){if(this.sabotage){jsonSend(ws,{t:'error',code:'sabotage_active',message:'关键破坏进行中，暂时不能封锁门禁'});return;}this.doorLockUntil=now+DOOR_LOCK_MS;this.sabotageReadyAt=now+this.settings.sabotageCooldown*1000;await this.persistNow();this.broadcast({t:'doors',until:this.doorLockUntil});this.broadcastState();await this.scheduleNextAlarm();return;}const d=SABOTAGE_DEFS[kind];if(!d)return;if(this.sabotage){jsonSend(ws,{t:'error',code:'sabotage_active',message:'已有破坏正在进行'});return;}this.sabotage={type:kind,startedAt:now,endsAt:d.durationMs?now+d.durationMs:0,fixedStations:[]};await this.persistNow();this.broadcast({t:'sabotage',sabotage:publicSabotage(this.sabotage)});this.broadcastState();await this.scheduleNextAlarm();}
  async fixSabotage(player,stationId,ws){if(this.phase!=='playing'||!this.sabotage||!player.alive||player.inVent)return;const d=SABOTAGE_DEFS[this.sabotage.type];if(!d||!d.stations.includes(stationId)||this.sabotage.fixedStations.includes(stationId))return;const o=OBJECT_DEFS.find(x=>x.id===stationId);if(!o||Math.hypot(player.pos.x-o.x,player.pos.y-o.y)>1.7)return;this.sabotage.fixedStations.push(stationId);const done=d.stations.every(id=>this.sabotage.fixedStations.includes(id));if(done){const label=d.label;this.sabotage=null;this.sabotageReadyAt=Date.now()+this.settings.sabotageCooldown*1000;await this.persistNow();this.broadcast({t:'sabotage',sabotage:null});this.broadcast({t:'notice',text:`${label} 已修复`});this.broadcastState();await this.scheduleNextAlarm();}else{await this.persistNow();this.broadcast({t:'sabotage',sabotage:publicSabotage(this.sabotage)});this.broadcastState();jsonSend(ws,{t:'repair_ok',stationId});}}
  async handleVent(player,action,ventId,ws){if(this.phase!=='playing'||player.role!=='impostor'||!player.alive)return;const now=Date.now();if(action==='enter'){if(player.inVent)return;const v=VENT_DEFS.find(x=>x.id===ventId);if(!v||Math.hypot(player.pos.x-v.x,player.pos.y-v.y)>1.15)return;player.inVent=true;player.ventId=v.id;player.pos={x:v.x,y:v.y};player.lastMoveAt=now;}else if(action==='travel'){if(!player.inVent)return;const from=VENT_DEFS.find(x=>x.id===player.ventId),to=VENT_DEFS.find(x=>x.id===ventId);if(!from||!to||!from.links.includes(to.id))return;player.ventId=to.id;player.pos={x:to.x,y:to.y};player.lastMoveAt=now;}else if(action==='exit'){if(!player.inVent)return;const v=VENT_DEFS.find(x=>x.id===player.ventId);if(!v)return;player.inVent=false;player.ventId='';player.pos={x:v.x,y:v.y};player.lastMoveAt=now;}else return;await this.persistNow();jsonSend(ws,{t:'vent_state',id:player.id,x:player.pos.x,y:player.pos.y,inVent:player.inVent,ventId:player.ventId});this.broadcast({t:'vent_state',id:player.id,x:player.pos.x,y:player.pos.y,inVent:player.inVent},player.id);}

  async endGame(winner,reason){if(this.phase==='ended')return true;this.phase='ended';this.winner=winner;this.reason=reason;this.endedAt=Date.now();this.meeting=null;this.sabotage=null;this.doorLockUntil=0;await this.persistNow();for(const p of Object.values(this.players))this.sendTo(p.id,{t:'game_over',winner,reason,selfState:this.selfState(p),roles:Object.fromEntries(Object.values(this.players).map(x=>[x.id,x.role]))});await this.scheduleNextAlarm();return true;}
  async checkWin(source){if(this.phase==='lobby'||this.phase==='ended')return false;const alive=Object.values(this.players).filter(p=>p.alive),imps=alive.filter(p=>p.role==='impostor'),crew=alive.filter(p=>p.role==='crewmate'),tasks=this.taskProgress();if(Object.values(this.players).some(p=>p.role==='impostor')&&imps.length===0)return this.endGame('crewmate','所有内鬼都已被淘汰');if(tasks.taskTotal>0&&tasks.taskDone>=tasks.taskTotal)return this.endGame('crewmate','所有船员任务已经完成');if(imps.length>0&&imps.length>=crew.length&&(source==='kill'||source==='vote'||source==='leave'))return this.endGame('impostor','内鬼人数已经不低于剩余船员');return false;}
  async resetLobby(player){if(player.id!==this.hostId||this.phase!=='ended')return;this.phase='lobby';this.winner='';this.reason='';this.startedAt=0;this.endedAt=0;this.meeting=null;this.bodies=[];this.sabotage=null;this.doorLockUntil=0;this.sabotageReadyAt=0;let i=0;for(const p of Object.values(this.players)){p.role='';p.alive=true;p.tasks=[];p.fakeTasks=[];p.completed=[];p.killReadyAt=0;p.emergencyUsed=0;p.inVent=false;p.ventId='';p.activeTask=null;p.pos=this.spawnForIndex(i++);p.lastMoveAt=Date.now();}await this.persistNow();this.broadcast({t:'lobby_reset',players:this.publicPlayers()});this.broadcastState();await this.scheduleNextAlarm();}

  async markDisconnected(ws){const a=ws.deserializeAttachment(),p=a?.playerId?this.players[a.playerId]:null;if(!p||!p.connected||(a?.connectionId&&p.connectionId!==a.connectionId))return;p.connected=false;p.lastSeen=Date.now();p.connectionId='';await this.persistNow();this.broadcastState();await this.scheduleNextAlarm();}
  async webSocketClose(ws){await this.markDisconnected(ws);}
  async webSocketError(ws){await this.markDisconnected(ws);}
  async alarm(){const now=Date.now(),changed=this.cleanupExpired(now);if(this.doorLockUntil&&now>=this.doorLockUntil){this.doorLockUntil=0;await this.persistNow();this.broadcast({t:'doors',until:0});this.broadcastState();}if(changed){if(!this.players[this.hostId])this.electHost();await this.persistNow();this.broadcastState();await this.checkWin('leave');}if(this.phase==='playing'&&this.sabotage?.endsAt&&now>=Number(this.sabotage.endsAt)){const label=SABOTAGE_DEFS[this.sabotage.type]?.label||'关键破坏';await this.endGame('impostor',`${label} 未能及时修复`);return;}if(this.phase==='meeting'&&this.meeting){if(this.meeting.stage==='voting'&&now>=this.meeting.votingEndsAt)await this.resolveMeeting();else if(this.meeting.stage==='result'&&now>=this.meeting.resumeAt)await this.resumeAfterMeeting();}await this.scheduleNextAlarm();}
}

export default {
  async fetch(request,env){const url=new URL(request.url);if(url.pathname==='/health')return Response.json({ok:true,service:'d1-realtime',version:'2.2'});if(url.pathname!=='/ws')return new Response('Not found',{status:404});const room=url.searchParams.get('room')||'';if(!/^\d{6}$/.test(room))return new Response('Bad room',{status:400});const id=env.ROOMS.idFromName(`room:${room}`);return env.ROOMS.get(id).fetch(request);}
};
