const fs=require('fs');
const src=fs.readFileSync('game.js','utf8');
const html=fs.readFileSync('index.html','utf8');
const css=fs.readFileSync('styles.css','utf8');
const headers=fs.readFileSync('_headers','utf8');
const hybrid=fs.readFileSync('hybrid-transport.js','utf8');
const playerCss=fs.readFileSync('player-shell.css','utf8');
const worker=fs.readFileSync('worker.js','utf8');
const polish=fs.readFileSync('game-polish.js','utf8');
const signalBudget=fs.readFileSync('signal-budget.js','utf8');
const signalWorker=fs.readFileSync('workers/p2p-signal-v2.js','utf8');
const server=fs.readFileSync('server/src/main.rs','utf8');

function assert(condition,message){if(!condition)throw new Error(`[2.8 test] ${message}`);}
function includes(haystack,needle,message){assert(haystack.includes(needle),message);}
function excludes(haystack,needle,message){assert(!haystack.includes(needle),message);}

includes(src,"const HEARTBEAT_INTERVAL = 3000",'RTT sampling interval must be 3 seconds');
includes(src,"const CONNECT_TIMEOUT_MS = 20000",'slow Cloudflare routes must get a 20 second websocket handshake budget');
includes(src,"ws.onclose=e=>{",'websocket close handler must receive the CloseEvent before reading its reason');
includes(src,"String(e?.reason||'').trim()||'无法建立实时连接'",'connection errors must preserve transport-specific close reasons');
excludes(src,"ws.onclose=()=>{if(generation!==socketGeneration)return;stopHeartbeat();if(connectReject)",'close handler must not drop the event argument');
excludes(src,"r(new Error('无法连接到实时服务器'))",'P2P failures must not be mislabeled as realtime server failures');
includes(src,"function renderLatency()",'frontend must display realtime RTT');
includes(src,"function recordLatency(sample)",'frontend must smooth RTT and jitter');
includes(src,"function sendAction(payload,syncPosition=true)",'critical actions must force a fresh position checkpoint');
includes(src,'function applyAuthoritativePlayers(raw,{acceptSelf=false}={})','authoritative player snapshots must have a single reconciliation path');
includes(src,'if(acceptSelf||awaitingAuthoritativeSelfPosition)','spawn and reset snapshots must override local prediction');
includes(src,'seq<=remoteMoveSeq[id]','stale movement packets must be rejected');
includes(src,'map:MAP_PROTOCOL_ID','every room connection must identify the canonical map protocol');
includes(src,'client:CLIENT_INSTANCE_ID','every room connection must carry a per-instance identity fence');
includes(src,"nav!=='reload'",'copied tabs must detect an already-live client instance instead of sharing its identity');
includes(src,"k.startsWith('au-dtam-tab-resume:')",'copied tabs must discard cloned resume credentials before connecting');
includes(src,"params.set('handoff',resumeHandoffFrom)",'stale local instances must hand off the resume token instead of losing reconnect');
includes(src,"navigator.locks?.request",'modern clients must use Web Locks for live instance ownership');
includes(src,"acquireHeldClientLock",'client ownership must use a held browser lock, not only timer leases');
includes(src,"await clientInstanceReady",'room connection must wait for client instance ownership to settle');
includes(src,"prepareResumeHandoff",'crash/restart recovery must prove the old browser instance is no longer live');
includes(src,"nav==='reload'?2500:0",'fast reloads must briefly wait for the previous document lock instead of losing identity');
includes(src,"acquireHeldClientLock(resumeHandoffFrom,2500)",'crash handoff must tolerate a short socket/document teardown race without allowing an unbounded takeover');
includes(server,'handoff_instance_id','Rust fallback must support explicit reconnect handoff');
includes(server,'legacy_unbound','Rust fallback must migrate pre-fencing live sessions without breaking reconnect');
includes(hybrid,'handoff===p.clientInstanceId','Auto P2P authority must allow an explicit stale-instance handoff');
includes(src,"code==='session_in_use'",'client must recover from a token already owned by another live instance');
includes(hybrid,"!(same||legacy||transfer)",'Auto browser-host authority must reject a live unrelated instance while permitting reconnect handoff');
includes(hybrid,"game.js?v=20260920-musicauto1",'transport must load the current session-fencing gameplay bundle');
includes(src,'directReady:p.directReady===true','Server direct readiness must be represented per player');
includes(src,'startGameBtn.disabled=count<2||waiting>0','Server matches must wait for every direct transport');
includes(src,"const POS_SEND_INTERVAL_DIRECT = 20",'direct P2P movement must target about 50 Hz');
includes(src,"const POS_SEND_INTERVAL_DIRECT_SLOW = 20",'high-RTT direct P2P must not be artificially throttled');
includes(src,"const POS_SEND_INTERVAL_RELAY = 40",'relay movement must stay conservative at about 25 Hz');
includes(src,"function positionSendInterval()",'movement send cadence must adapt to the selected path');
includes(src,"const REMOTE_PREDICTION_MAX_MS = 110",'remote movement prediction must remain bounded while covering high direct RTT');
includes(src,"const REMOTE_SMOOTHING_DIRECT = 54",'healthy direct P2P must converge remote visuals aggressively');
includes(src,"const REMOTE_SMOOTHING_DIRECT_SLOW = 50",'slow direct P2P must not become visibly sluggish');
includes(src,"const REMOTE_SMOOTHING_RELAY = 34",'relay smoothing must avoid excessive jitter amplification');
includes(src,"function remoteSmoothingRate()",'remote smoothing must adapt to the selected path');
excludes(headers,'microphone=()','Pages headers must not disable microphone');
includes(headers,'microphone=(self)','same-origin microphone permission must be allowed');
includes(html,'/styles.css?v=20260829-ux1','current UX cache-busted stylesheet must be loaded');
includes(html,'/hybrid-transport.js?v=20260920-hostattach1','current transport entry must be loaded');
excludes(headers,'immutable','runtime assets must never pin mixed protocol versions');
includes(headers,'Cache-Control: no-cache, max-age=0, must-revalidate','runtime assets must revalidate');
includes(html,'maxlength="2"','room input must be two digits');
includes(html,'pattern="[0-9]{2}"','room input must validate two digits');
excludes(html,'gameplay-2.','legacy versioned CSS must not be loaded');
excludes(css,'.voice-sink{display:none!important}','remote audio must never be removed from the render tree');
includes(css,'#actionStack #killBtn { order: 5;','kill button position must be stable');
includes(css,'#actionStack #reportBtn { order: 6;','report must not replace kill under the finger');
excludes(playerCss,'#latencyStatus { display: none','latency must stay visible on compact devices');
includes(src,'id="lobbyInviteBtn"','lobby must expose a first-class invite action');
includes(src,'data-rule-preset="classic"','lobby must expose playable rule presets');
includes(src,'function applyRulePreset(name)','rule presets must be functional, not decorative');
includes(src,'value="15" selected>15 秒</option>','default discussion time must exist and show units');
includes(src,'function handleGameShortcut(e)','desktop gameplay shortcuts must be wired');
includes(src,'const PLAYER_VISUAL_RADIUS = 0.56','player sprites must have a readable visual size without changing collision radius');
includes(src,'function drawObjectiveHint(view,p)','offscreen tasks and urgent repairs must have direction guidance');
includes(src,"label=pl.id===myPlayerId?'你':shown.name",'the local player label must stay concise in crowded spawns');
includes(hybrid,"game.js?v=20260920-musicauto1",'transport must load the current gameplay/performance bundle');
includes(hybrid,"game-polish.js?v=20260918-archmusic1",'transport must load the current polish bundle');
includes(playerCss,'DTAM UX FLOW 20260829','player shell must include the current lobby layout layer');
excludes(polish,'stopImmediatePropagation()','typing, shortcuts, and IME input must not be swallowed by a capture guard');
includes(polish,"u.searchParams.set('room',code)",'copied invite links must carry the room code');

includes(hybrid,"const FAST_OUT=new Set(['pos','ping'])",'P2P position and RTT probes must use the fast channel');
includes(hybrid,"createDataChannel('dtam-fast',{ordered:false,maxRetransmits:0,priority:'high'})",'fast P2P channel must be unordered, non-retransmitting and high-priority');
includes(hybrid,'JOIN_POLL=900','doorbell fallback polling must not impose multi-second lobby join latency');
includes(hybrid,'diag.transportRttMs=m.rttMs','guest WebRTC must publish selected candidate-pair RTT');
includes(hybrid,'diag.relay=m.relay','guest WebRTC must report TURN relay selection accurately');
includes(src,'s=300/NETWORK_MAP_SIZE','full minimap must render the authoritative network collision grid');
includes(src,'ensureWorldWallLayer(p)','main world must render the authoritative collision grid through a cached wall layer');
includes(src,'NETWORK_MAP_DATA[row*NETWORK_MAP_SIZE+col]===1','cached world wall layer must derive from authoritative collision cells');
excludes(src,'FRAME_INTERVAL_MS','main loop must follow display requestAnimationFrame without high-refresh frame skipping');
includes(hybrid,'__dtamRecovery','P2P transport must carry recovery snapshots');
includes(hybrid,'sendSnapshotTo','host must be able to push recovery snapshot to a hot standby');
includes(worker,'async startMeeting(player','browser authority must handle meetings');
includes(worker,'broadcastVoiceDirectory(){','browser authority must maintain the voice directory');
includes(worker,"this.phase==='playing'||this.phase==='meeting'",'meeting phase must remain active-game context for ghost isolation');

includes(src,'function roleCapacity(st,count)','lobby must validate role capacity before starting');
includes(src,'职业数量会按当前人数校验；超出可用名额时需调整后才能开始。','lobby copy must describe hard role-capacity validation');
excludes(src,'由服务器自动裁剪','lobby must not claim impossible role settings are silently clipped');
includes(src,'canSeePlayerPosition(myPos,pos)','client action targeting must respect wall line-of-sight and bush concealment');
includes(src,'taskRequestTimer=setTimeout','task loading must have a bounded request timeout');
includes(src,'closeToolOverlays(true)','meeting/end transitions must force-close stale gameplay overlays');
includes(src,'id="endRoster"','end screen must reveal the final role roster');
includes(src,"if(msg.t==='action_fail')",'authoritative action rejection must surface to the player');
includes(src,"if(msg.t==='guardian_assigned')",'ejected guardian assignment must be visible to the player');
includes(css,'#meetingOverlay { z-index: 90; }','meeting overlay must outrank ordinary tool overlays');
includes(css,'#endOverlay { z-index: 92; }','end overlay must outrank in-game overlays');
includes(worker,'actionFail(ws,code,message)','authority must support nonfatal action feedback');
includes(worker,'assignGuardian(player,now=Date.now())','guardian assignment must share one authoritative path');
includes(worker,'updateMeetingEligibility()','meeting eligibility must react to disconnects');
includes(worker,'p.activeTask=null;','meetings must invalidate active task challenges');
includes(worker,"'role_capacity'",'authority must reject impossible role configurations rather than silently clipping');
includes(worker,"t:'repair_ok',stationId,done",'final sabotage repair must acknowledge the repairing player');
includes(worker,"t:'guardian_assigned'",'vote ejection must be able to assign guardian angel');
includes(src,"requestedNameValid=v=>!/\\d$/.test(sanitizeName(v))",'requested nicknames must not end in digits');
includes(worker,'uniquePlayerName(players,base)','browser authority must allocate duplicate display-name suffixes');
includes(server,'fn unique_player_name(room: &Room, base: &str)','Rust authority must allocate duplicate display-name suffixes');
includes(hybrid,"find(x=>x.token===token)",'resume identity must be token-based rather than display-name-based');
includes(hybrid,"tryServerPrimary()",'Auto transport must probe the independent Server first');
includes(hybrid,"m?.features?.serverPrimaryV2!==true",'Auto must reject an outdated live Server before adopting it as primary');
includes(hybrid,"const attached=await attach(this.auth,this.local,this.params);this.open(attached?'browser-host':'p2p-error')",'browser host must attach authority identity before exposing WebSocket open');
includes(hybrid,"d=>this.opened?this.deliver(d):pending.push(String(d))",'browser host must buffer welcome/state packets until the WebSocket open event');
includes(server,'"serverPrimaryV2":true','current Rust authority must advertise the server-primary capability gate');
includes(worker,'p2pFallbackV2:true','browser authority must advertise current P2P fallback capabilities');
includes(hybrid,"room_not_found')return abandon('房间不在 Server，转 P2P')",'Server absence of a fallback-created room must fall through to P2P');
includes(hybrid,'startHeartbeat()','P2P fallback authority must maintain a low-rate liveness lease');
includes(hybrid,'.slice(0,2)','P2P fallback must keep two recovery standbys');
includes(src,'function bushRegionAt(pos)','client must model bush concealment regions');
includes(src,'function canSeePlayerPosition(viewer,target)','client visibility must combine wall LOS with bush concealment');
includes(worker,'function canSeePlayer(a,b,doorsClosed=false)','browser authority must enforce bush concealment');
includes(server,'fn can_see_player(a: &Pos, b: &Pos, doors_closed: bool)','Rust authority must enforce bush concealment');
includes(src,"music.id='musicPlayer'",'client must expose the shared mini soundtrack player');
includes(src,"musicAsset(name,ext){return '/assets/music/'",'soundtrack media must be served as static Pages assets');
includes(src,'function normalizeMusicTrack(v)','soundtrack client must consume generated asset paths');
includes(src,"musicMedia.dataset.src!==src",'soundtrack player must switch when generated media path changes');
const musicGenerator=fs.readFileSync('scripts/generate-music-manifest.cjs','utf8');
includes(musicGenerator,"fs.readdirSync(MUSIC_DIR",'music manifest must be generated by scanning the asset directory');
includes(musicGenerator,"schema: 2",'generated music manifest must use schema 2');
includes(src,"musicControl:ruleMusicControl.value==='host'?'host':'all'",'waiting room must select host-only or all-player soundtrack control');
includes(worker,"if(msg.t==='music')",'browser authority must synchronize music state');
includes(server,'"music" => {','Rust authority must synchronize music state');
includes(playerCss,'@keyframes dtam-cover-groove','soundtrack cover must animate while playing');
includes(html,'/signal-budget.js?v=20260919-lowcf1','Pages must load the low-CF join budget policy');
includes(signalBudget,'const BELL_VISIBLE_MS = 8000','healthy doorbell must reduce D1 join polling to a slow safety net');
includes(signalBudget,"window.__DTAM_BELL__",'join budget must react to live doorbell health');
includes(signalWorker,"version:'2.4'",'deployed signalling source must expose the optimized version');
includes(signalWorker,'LEFT JOIN peers p ON p.room=r.room','hot host mailbox reads must use a single D1 query');


console.log('[2.8 test] ok');
