const fs=require('node:fs');
const vm=require('node:vm');
const crypto=require('node:crypto').webcrypto;
const {TextEncoder,TextDecoder}=require('node:util');
const root=process.cwd();
const assert=(ok,message)=>{if(!ok)throw new Error(`[roles] ${message}`)};
const source=fs.readFileSync(`${root}/worker.js`,'utf8').replace(/^export class GameRoom/m,'class GameRoom');
const workerCode=source.slice(0,source.indexOf('\nexport default'))+'\nglobalThis.__GameRoom=GameRoom;';
const workerContext=vm.createContext({console:{log(){},warn(){}},crypto,TextEncoder,TextDecoder,structuredClone,Date,Math,URL,URLSearchParams,Response,Request,Headers,setTimeout,clearTimeout,setInterval,clearInterval,fetch:async()=>new Response(null,{status:404})});
vm.runInContext(workerCode,workerContext,{filename:'worker.js'});
const Room=workerContext.__GameRoom;
let assertions=0;
function check(ok,message){assertions++;assert(ok,message);}
const now=Date.now();
const pos=(x=75.5,y=75.5)=>({x,y});
function player(id,role,opts={}){return{id,name:id,role,ghostRole:'',connected:true,connectionId:`c-${id}`,alive:true,inVent:false,ventId:'',pos:pos(),moveSeq:0,lastMoveAt:now,abilityReadyAt:0,abilityUntil:0,hiddenUntil:0,disguiseTargetId:'',trackedId:'',trackUntil:0,ventReadyAt:0,ventExitAt:0,protectedUntil:0,lastCaseId:'',lastCaseArea:'',emergencyUsed:0,...opts};}
function roomWith(...people){const room=Object.create(Room.prototype);room.phase='playing';room.players=Object.fromEntries(people.map(p=>[p.id,p]));room.bodies=[];room.settings={killCooldown:20,emergencyMeetings:1,guardianAngels:0};room.hostId=people[0]?.id||'';room.meeting=null;room.sabotage=null;room.doorLockUntil=0;room.persistNow=async()=>{};room.scheduleNextAlarm=async()=>{};room.broadcast=()=>{};room.broadcastState=()=>{};room.sendTo=()=>{};room.sendError=()=>{};room.startMeeting=async(...args)=>{room.meeting={args};room.phase='meeting';};room.checkWin=async()=>{};room.cleanupExpired=()=>false;room.electHost=()=>{};return room;}
function socketFor(p){const messages=[];return{messages,deserializeAttachment:()=>({playerId:p.id,connectionId:p.connectionId}),send(raw){messages.push(JSON.parse(raw));}};}
async function packet(room,p,t,payload={}){const ws=socketFor(p);await room.webSocketMessage(ws,JSON.stringify({t,...payload}));return ws.messages;}
function has(messages,t,code){return messages.some(m=>m.t===t&&(!code||m.code===code));}

// The actual frontend target picker and click handler are evaluated from game.js source.
const game=fs.readFileSync(`${root}/game.js`,'utf8');
const pickerStart=game.indexOf('function nearestAbilityTarget(){');
const pickerEnd=game.indexOf('\nfunction ',pickerStart+12);
const clickStart=game.indexOf('abilityBtn.onclick=()=>{');
const clickEnd=game.indexOf(';taskHoldBtn.addEventListener',clickStart);
const nameStart=game.indexOf('function visiblePlayerName(player){');
const nameEnd=game.indexOf('\nfunction ',nameStart+12);
const renderStart=game.indexOf('function renderActions(){');
const renderEnd=game.indexOf('\nfunction ',renderStart+12);
const openVitalsStart=game.indexOf('function openVitals(){');
const openVitalsEnd=game.indexOf('\nfunction ',openVitalsStart+12);
const closeVitalsStart=game.indexOf('function closeVitals(){');
const closeVitalsEnd=game.indexOf('\nfunction ',closeVitalsStart+12);
const renderVitalsStart=game.indexOf('function renderVitals(){');
const renderVitalsEnd=game.indexOf('\nfunction ',renderVitalsStart+12);
assert(pickerStart>=0&&pickerEnd>pickerStart&&clickStart>=0&&clickEnd>clickStart&&nameStart>=0&&nameEnd>nameStart&&renderStart>=0&&renderEnd>renderStart&&openVitalsStart>=0&&openVitalsEnd>openVitalsStart&&closeVitalsStart>=0&&closeVitalsEnd>closeVitalsStart&&renderVitalsStart>=0&&renderVitalsEnd>renderVitalsStart,'could not extract actual game.js role picker, action renderer, display-name helper, click handler, or vitals functions');
const gameContext=vm.createContext({Date,Math,players:{},remoteVisuals:{},myPlayerId:'self',myPos:pos(),gameState:{phase:'playing'},selfState:{alive:true,role:'tracker'},NETWORK_TO_CLIENT:1,canSeePlayerPosition:()=>true,playButtonClick(){},claimAction:()=>true,abilityBtn:{},vitalsOverlay:{classList:{contains:()=>false}},scientistBattery:75,closeVitals(){},openVitals(){},showToast(){},sendAction(payload){gameContext.__sent.push(payload);},__sent:[]});
vm.runInContext(`${game.slice(pickerStart,pickerEnd)}\n${game.slice(clickStart,clickEnd)};globalThis.__picker=nearestAbilityTarget;`,gameContext,{filename:'game.js role functions'});
function frontendTarget(role,alive,ghostRole,people,protectableIds){gameContext.players=Object.fromEntries(people.map(p=>[p.id,p]));gameContext.selfState={alive,role,ghostRole,protectableIds};gameContext.__sent=[];return gameContext.__picker();}
const roleButton=()=>({hidden:false,disabled:false,textContent:'',title:'',classList:{toggle(){}}});
const renderContext=vm.createContext({Date,Math,players:{},myPlayerId:'self',myPos:pos(),remoteVisuals:{},gameState:{phase:'playing',settings:{}},selfState:{alive:true,role:'tracker',abilityReadyAt:0,trackUntil:0},networkPaused:false,reportBlockedUntil:0,ROLE_META:{tracker:{action:'追踪'},guardian:{action:'保护'}},isImpostorRole:()=>false,meetingUiActive:()=>false,nearestBody:()=>null,nearestKillTarget:()=>null,nearestAbilityTarget:()=>null,nearestAssignedTask:()=>null,nearestSabotageStation:()=>null,nearestVent:()=>null,nearbyInfo:()=>null,nearEmergencyConsole:()=>null,canEmergency:()=>false,mapBtn:roleButton(),reportBtn:roleButton(),killBtn:roleButton(),abilityBtn:roleButton(),sabotageBtn:roleButton(),ventBtn:roleButton(),infoBtn:roleButton(),interactBtn:roleButton()});
vm.runInContext(`${game.slice(nameStart,nameEnd)}\n${game.slice(renderStart,renderEnd)}\nglobalThis.__renderActions=renderActions;globalThis.__visiblePlayerName=visiblePlayerName;`,renderContext,{filename:'game.js render role action'});
vm.runInContext(game.slice(clickStart,clickEnd),renderContext,{filename:'game.js actual ability click handler'});
const vitalsOverlay={shown:false,classList:{add(name){if(name==='show')vitalsOverlay.shown=true;},remove(name){if(name==='show')vitalsOverlay.shown=false;},contains(name){return name==='show'&&vitalsOverlay.shown;}}};
const vitalsContext=vm.createContext({Date,Math,players:{},selfState:{alive:true,role:'scientist',inVent:false},gameState:{phase:'playing'},networkPaused:false,scientistBattery:100,vitalsOverlay,vitalsGrid:{innerHTML:''},vitalsTimer:null,meetingUiActive:()=>false,updateVitalsBatteryUI(){},renderActions(){},renderVitals:null,showToast(){},setInterval:()=>17,clearInterval(){},avatarMarkup:p=>p.name,escapeHtml:x=>String(x)});
vm.runInContext(`${game.slice(openVitalsStart,openVitalsEnd)}\n${game.slice(closeVitalsStart,closeVitalsEnd)}\n${game.slice(renderVitalsStart,renderVitalsEnd)}\nglobalThis.__openVitals=openVitals;globalThis.__closeVitals=closeVitals;globalThis.__renderVitals=renderVitals;`,vitalsContext,{filename:'game.js production vitals functions'});

(async()=>{
  const impostor=player('imp','shapeshifter'),visible=player('visible','crewmate',{pos:pos(76,75.5)}),hidden=player('hidden','crewmate',{pos:pos(76.1,75.5),hiddenUntil:now+60000}),inVent=player('vented','crewmate',{pos:pos(76.2,75.5),inVent:true});
  let r=roomWith(impostor,visible,hidden,inVent),m=await packet(r,impostor,'ability',{targetId:'hidden'});check(has(m,'action_fail','ability_target')&&!impostor.disguiseTargetId,'shapeshifter rejects hidden target');
  m=await packet(r,impostor,'ability',{targetId:'vented'});check(has(m,'action_fail','ability_target')&&!impostor.disguiseTargetId,'shapeshifter rejects in-vent target');
  m=await packet(r,impostor,'ability',{targetId:'visible'});check(has(m,'ability_ok')&&impostor.disguiseTargetId==='visible'&&impostor.abilityUntil>now,'shapeshifter accepts visible target and starts timed disguise');
  m=await packet(r,impostor,'ability',{targetId:'visible'});check(has(m,'error','ability_cooldown'),'shapeshifter cooldown enforced');

  const phantom=player('phantom','phantom');r=roomWith(phantom);m=await packet(r,phantom,'ability');check(has(m,'ability_ok')&&phantom.hiddenUntil>now&&phantom.abilityUntil===phantom.hiddenUntil,'phantom invisibility has authoritative expiry');
  const tracker=player('tracker','tracker');r=roomWith(tracker,visible,hidden,inVent);m=await packet(r,tracker,'ability',{targetId:'hidden'});check(has(m,'action_fail','ability_target')&&!tracker.trackedId,'tracker rejects hidden target');m=await packet(r,tracker,'ability',{targetId:'vented'});check(has(m,'action_fail','ability_target')&&!tracker.trackedId,'tracker rejects in-vent target');m=await packet(r,tracker,'ability',{targetId:'visible'});check(has(m,'ability_ok')&&tracker.trackedId==='visible'&&tracker.trackUntil>now,'tracker establishes timed mark on visible target');
  const detective=player('detective','detective');visible.lastCaseId='case-1';visible.lastCaseArea='dock';r=roomWith(detective,visible,hidden,inVent);m=await packet(r,detective,'ability',{targetId:'hidden'});check(has(m,'action_fail','ability_target')&&!has(m,'detective_result'),'detective rejects hidden target');m=await packet(r,detective,'ability',{targetId:'vented'});check(has(m,'action_fail','ability_target')&&!has(m,'detective_result'),'detective rejects in-vent target');m=await packet(r,detective,'ability',{targetId:'visible'});check(has(m,'detective_result')&&has(m,'ability_ok'),'detective returns case information for visible target');

  const scientist=player('scientist','scientist');r=roomWith(scientist);m=await packet(r,scientist,'ability');check(has(m,'ability_ok')&&scientist.abilityUntil>now,'living scientist ability route succeeds');
  scientist.alive=false;scientist.trackUntil=Date.now()+60000;const crew=player('crew','crewmate',{name:'船员',pos:pos(76,75.5)}),crew2=player('crew2','engineer',{pos:pos(76.2,75.5)}),imp2=player('imp2','impostor',{pos:pos(76.1,75.5)});r=roomWith(scientist,crew,crew2,imp2);r.settings.guardianAngels=1;check(r.assignGuardian(scientist,Date.now())&&scientist.ghostRole==='guardian','actual guardian assignment accepts dead scientist with crew role and available capacity');scientist.abilityReadyAt=0;
  const state=r.selfState(scientist);check(Array.isArray(state.protectableIds)&&state.protectableIds.includes('crew')&&state.protectableIds.includes('crew2')&&!state.protectableIds.includes('imp2'),'dead guardian self state lists only connected living crew');
  check(frontendTarget('scientist',false,'guardian',[crew,crew2,imp2],state.protectableIds)?.id==='crew','dead scientist guardian frontend picker selects eligible crew');
  gameContext.selfState={alive:false,role:'scientist',ghostRole:'guardian',abilityReadyAt:0,abilityUntil:now+60000,trackUntil:now+60000};gameContext.nearestAbilityTarget=()=>crew;gameContext.__sent=[];vm.runInContext('abilityBtn.onclick()',gameContext);check(gameContext.__sent.some(x=>x.t==='ability'&&x.targetId==='crew'),'dead scientist guardian button sends guardian target ability');
  renderContext.players={crew};renderContext.selfState={alive:false,role:'scientist',ghostRole:'guardian',abilityReadyAt:0,abilityUntil:Date.now()+60000,trackUntil:Date.now()+60000};renderContext.nearestAbilityTarget=()=>crew;renderContext.__renderActions();check(!renderContext.abilityBtn.hidden&&!renderContext.abilityBtn.disabled&&renderContext.abilityBtn.textContent==='保护 船员','actual renderActions shows enabled guardian action for dead scientist and ignores stale ability/track timers');renderContext.__sent=[];renderContext.sendAction=payload=>renderContext.__sent.push(payload);renderContext.claimAction=()=>true;renderContext.playButtonClick=()=>{};renderContext.abilityBtn.onclick();check(renderContext.__sent.some(x=>x.t==='ability'&&x.targetId==='crew'),'rendered dead-scientist guardian button callback targets selected crew');
  m=await packet(r,scientist,'ability',{targetId:'crew'});check(has(m,'ability_ok')&&crew.protectedUntil>now,'guardian protects crew through server handler');
  const deadNotGuardian=player('dead','scientist',{alive:false});crew.protectedUntil=0;r=roomWith(deadNotGuardian,crew);m=await packet(r,deadNotGuardian,'ability',{targetId:'crew'});check(!has(m,'ability_ok')&&!crew.protectedUntil,'dead non-guardian cannot use ability');
  const assignmentRoom=roomWith(),eligibleOne=player('eligible-one','scientist',{alive:false}),eligibleTwo=player('eligible-two','engineer',{alive:false}),impostorGhost=player('impostor-ghost','impostor',{alive:false});assignmentRoom.players={eligibleOne,eligibleTwo,impostorGhost};assignmentRoom.settings.guardianAngels=1;check(assignmentRoom.assignGuardian(eligibleOne,Date.now())&&!assignmentRoom.assignGuardian(eligibleTwo,Date.now()),'actual guardian assignment enforces configured capacity');check(!assignmentRoom.assignGuardian(impostorGhost,Date.now())&&!impostorGhost.ghostRole,'actual guardian assignment rejects non-crew roles');

  function vitalsAttempt({alive=true,role='scientist',inVent=false,phase='playing',paused=false,battery=100}={}){vitalsOverlay.shown=false;vitalsContext.selfState={alive,role,inVent};vitalsContext.gameState={phase};vitalsContext.networkPaused=paused;vitalsContext.scientistBattery=battery;vitalsContext.__openVitals();return vitalsOverlay.shown;}
  check(vitalsAttempt(),'actual scientist openVitals opens during valid live play');vitalsContext.players={crew};vitalsContext.__renderVitals();check(vitalsOverlay.shown&&vitalsContext.vitalsGrid.innerHTML.includes('船员'),'actual renderVitals renders connected player rows while available');
  check(!vitalsAttempt({alive:false})&&!vitalsAttempt({role:'tracker'})&&!vitalsAttempt({phase:'meeting'})&&!vitalsAttempt({inVent:true})&&!vitalsAttempt({paused:true})&&!vitalsAttempt({battery:0}),'actual openVitals blocks dead, non-scientist, meeting, vent, paused, and empty-battery states');
  function vitalsRenderAttempt({alive=true,role='scientist',inVent=false,phase='playing',paused=false,battery=100}={}){vitalsOverlay.shown=true;vitalsContext.selfState={alive,role,inVent};vitalsContext.gameState={phase};vitalsContext.networkPaused=paused;vitalsContext.scientistBattery=battery;vitalsContext.__renderVitals();return vitalsOverlay.shown;}
  check(!vitalsRenderAttempt({alive:false})&&!vitalsRenderAttempt({role:'tracker'})&&!vitalsRenderAttempt({phase:'meeting'})&&!vitalsRenderAttempt({inVent:true})&&!vitalsRenderAttempt({paused:true})&&!vitalsRenderAttempt({battery:0}),'actual renderVitals closes for dead, non-scientist, meeting, vent, paused, and empty-battery states');

  const engineer=player('engineer','engineer',{pos:pos(30.5,30.5)});r=roomWith(engineer);m=await packet(r,engineer,'vent',{action:'enter',ventId:'vent-nw'});check(has(m,'vent_state')&&engineer.inVent&&engineer.ventExitAt>now,'engineer enters mapped vent with deadline');const ventDeadline=engineer.ventExitAt;m=await packet(r,engineer,'vent',{action:'exit'});check(has(m,'vent_state')&&!engineer.inVent&&engineer.ventExitAt===0&&engineer.ventReadyAt>now,'engineer manual exit clears deadline and starts cooldown');m=await packet(r,engineer,'vent',{action:'enter',ventId:'vent-nw'});check(has(m,'action_fail','vent_cooldown')&&!engineer.inVent,'engineer vent cooldown enforced');
  engineer.ventReadyAt=0;m=await packet(r,engineer,'vent',{action:'enter',ventId:'vent-nw'});check(engineer.inVent&&engineer.ventExitAt>=ventDeadline,'engineer can re-enter after cooldown');await r.ejectExpiredEngineers(engineer.ventExitAt+1);check(!engineer.inVent&&!engineer.ventId&&engineer.ventExitAt===0&&engineer.ventReadyAt>ventDeadline,'expired engineer is automatically ejected and state is cleared');
  engineer.ventReadyAt=0;m=await packet(r,engineer,'vent',{action:'enter',ventId:'vent-nw'});const cleaner=player('cleaner','crewmate',{pos:pos(30.5,30.5),tasks:['clean-vent-nw'],completed:[]});r.players.cleaner=cleaner;m=await packet(r,cleaner,'task_begin',{id:'clean-vent-nw'});check(has(m,'task_challenge')&&cleaner.activeTask?.type==='clean_vent'&&!engineer.inVent&&engineer.ventExitAt===0,'starting actual vent-clean task ejects engineer and clears deadline');engineer.ventReadyAt=0;m=await packet(r,engineer,'vent',{action:'enter',ventId:'vent-nw'});check(has(m,'action_fail','vent_cleaning')&&!engineer.inVent,'engineer cannot enter while that vent is being cleaned');cleaner.activeTask=null;m=await packet(r,engineer,'vent',{action:'enter',ventId:'vent-nw'});check(has(m,'vent_state')&&engineer.inVent,'engineer can enter again after vent cleaning ends');
  const saved=player('saved-eng','engineer',{inVent:true,ventId:'vent-nw',ventExitAt:Date.now()+60000,abilityUntil:Date.now()+30000,hiddenUntil:Date.now()+20000});const savedDeadlines={ventExitAt:saved.ventExitAt,abilityUntil:saved.abilityUntil,hiddenUntil:saved.hiddenUntil};const restoreRoom=Object.create(Room.prototype);restoreRoom.restore({players:{[saved.id]:saved}});check(restoreRoom.players[saved.id].ventExitAt===savedDeadlines.ventExitAt&&restoreRoom.players[saved.id].abilityUntil===savedDeadlines.abilityUntil&&restoreRoom.players[saved.id].hiddenUntil===savedDeadlines.hiddenUntil,'authority restore preserves role expiry timestamps against independent expected values');
  const missing=player('missing-eng','engineer',{inVent:true,ventId:'vent-nw',ventExitAt:0});restoreRoom.restore({players:{[missing.id]:missing}});const due=restoreRoom.players[missing.id].ventExitAt;check(due>0&&due<=Date.now()+1000,'restored vent occupant with missing deadline is due immediately');restoreRoom.sendTo=()=>{};restoreRoom.broadcast=()=>{};restoreRoom.persistNow=async()=>{};await restoreRoom.ejectExpiredEngineers(Date.now()+1);check(!restoreRoom.players[missing.id].inVent,'missing engineer deadline cannot trap player indefinitely');

  const viper=player('viper','viper'),victim=player('victim','crewmate',{pos:pos(76,75.5)});r=roomWith(viper,victim);m=await packet(r,viper,'kill',{targetId:victim.id});check(has(m,'kill_ok')&&!victim.alive&&r.bodies[0].dissolveAt>now,'viper kill creates dissolving corpse');const reporter=player('reporter','crewmate',{pos:pos(76,75.5)});r.players.reporter=reporter;r.bodies[0].dissolveAt=Date.now()-1;m=await packet(r,reporter,'report',{bodyId:r.bodies[0].id});check(has(m,'action_fail','body_gone')&&!r.meeting,'expired viper corpse cannot be reported before alarm cleanup');await r.dissolveBodies(Date.now());check(r.bodies.length===0,'alarm corpse cleanup removes dissolved body');

  const noisy=player('noisy','noisemaker'),killer=player('killer','impostor'),noisyVictim=player('noisyVictim','noisemaker',{pos:pos(76,75.5)});r=roomWith(killer,noisyVictim,noisy);const notices=[];r.sendTo=(id,payload)=>notices.push({id,payload});m=await packet(r,killer,'kill',{targetId:noisyVictim.id});check(notices.some(x=>x.id==='noisy'&&x.payload.t==='noisemaker'&&x.payload.until>Date.now()),'noisemaker death sends a timed alert to crew');
  const shieldAngel=player('shield-angel','crewmate',{alive:false,ghostRole:'guardian',pos:pos(75.5,75.5)}),shieldTarget=player('shield-target','crewmate',{pos:pos(76,75.5)}),shieldKiller=player('shield-killer','impostor',{pos:pos(76.1,75.5)});r=roomWith(shieldAngel,shieldTarget,shieldKiller);m=await packet(r,shieldAngel,'ability',{targetId:shieldTarget.id});check(has(m,'ability_ok')&&shieldTarget.protectedUntil>Date.now(),'guardian fixture receives shield before hostile hit');const hitTime=Date.now();m=await packet(r,shieldKiller,'kill',{targetId:shieldTarget.id});check(has(m,'kill_blocked')&&shieldTarget.alive&&shieldTarget.protectedUntil===0&&shieldTarget.protectedBy===''&&shieldKiller.killReadyAt-hitTime>=10000&&shieldKiller.killReadyAt-hitTime<=10100,`actual kill handler consumes guardian shield and reflects exact ten-second attack cooldown: ${JSON.stringify({m,shieldTarget,shieldKiller,hitTime})}`);m=await packet(r,shieldKiller,'kill',{targetId:shieldTarget.id});check(has(m,'action_fail','kill_cooldown')&&shieldTarget.alive,'reflected ten-second kill cooldown blocks repeated attack');shieldKiller.killReadyAt=Date.now()-1;m=await packet(r,shieldKiller,'kill',{targetId:shieldTarget.id});check(has(m,'kill_ok')&&!shieldTarget.alive,'kill succeeds after reflected cooldown expires');
  const guardian=player('guardian','impostor',{alive:false,ghostRole:'guardian'}),protectedCrew=player('protected','crewmate',{protectedUntil:0});r=roomWith(guardian,protectedCrew);m=await packet(r,guardian,'ability',{targetId:'protected'});check(has(m,'ability_ok')&&protectedCrew.protectedUntil>Date.now(),'guardian protection ability grants shield');

  const nonPlaying=player('phase','tracker'),phaseTarget=player('phase-target','crewmate',{pos:pos(76,75.5)});r=roomWith(nonPlaying,phaseTarget);r.phase='meeting';m=await packet(r,nonPlaying,'ability',{targetId:phaseTarget.id});check(!has(m,'ability_ok')&&!nonPlaying.trackedId,'ability denied during meeting');r.phase='ended';m=await packet(r,nonPlaying,'ability',{targetId:phaseTarget.id});check(!has(m,'ability_ok')&&!nonPlaying.trackedId,'ability denied after game end');r.phase='playing';nonPlaying.abilityReadyAt=Date.now()+30000;m=await packet(r,nonPlaying,'ability',{targetId:phaseTarget.id});check(has(m,'error','ability_cooldown')&&!nonPlaying.trackedId,'role ability cooldown enforced');
  const livingTarget=player('living','crewmate',{pos:pos(76,75.5)});for(const [role,field] of [['shapeshifter','disguiseTargetId'],['tracker','trackedId'],['detective','lastCaseId']]){const actor=player(`cd-${role}`,role,{abilityReadyAt:Date.now()+30000});r=roomWith(actor,livingTarget);m=await packet(r,actor,'ability',{targetId:livingTarget.id});check(has(m,'error','ability_cooldown')&&(!actor[field]||actor[field]===''),'cooldown blocks '+role+' ability');}

  const uiCrew=player('ui-crew','crewmate',{pos:pos(76,75.5)}),uiHidden=player('ui-hidden','crewmate',{pos:pos(76.1,75.5),hiddenUntil:Date.now()+60000}),uiVent=player('ui-vent','crewmate',{pos:pos(76.2,75.5),inVent:true});
  check(frontendTarget('shapeshifter',true,'',[uiCrew,uiHidden,uiVent])?.id==='ui-crew','front-end morph target picker skips hidden and in-vent players');
  check(frontendTarget('tracker',true,'',[uiCrew,uiHidden,uiVent])?.id==='ui-crew','front-end tracker target picker skips hidden and in-vent players');
  check(frontendTarget('detective',true,'',[uiCrew,uiHidden,uiVent])?.id==='ui-crew','front-end detective target picker skips hidden and in-vent players');
  check(frontendTarget('scientist',true,'',[uiCrew,uiHidden,uiVent])===null,'living scientist does not enter target-selection path');
  check(frontendTarget('scientist',false,'',[uiCrew])===null,'dead scientist without guardian does not enter target-selection path');
  const decoy={id:'decoy',name:'伪装身份'},shapeshifted={id:'shifter',name:'真实身份',connected:true,alive:true,inVent:false,pos:pos(76,75.5),abilityUntil:Date.now()+30000,disguiseTargetId:'decoy'};renderContext.players={decoy,shifter:shapeshifted};renderContext.selfState={alive:true,role:'tracker',abilityReadyAt:0,trackUntil:0};renderContext.nearestAbilityTarget=()=>shapeshifted;renderContext.__sent=[];renderContext.sendAction=payload=>renderContext.__sent.push(payload);renderContext.playButtonClick=()=>{};renderContext.claimAction=()=>true;renderContext.vitalsOverlay={classList:{contains:()=>false}};renderContext.scientistBattery=75;renderContext.closeVitals=()=>{};renderContext.openVitals=()=>{};renderContext.showToast=()=>{};
  check(renderContext.__visiblePlayerName(shapeshifted)==='伪装身份','active disguise resolves to displayed false identity');renderContext.__renderActions();check(renderContext.abilityBtn.textContent==='追踪 伪装身份','ability button label uses active disguised display name');vm.runInContext('abilityBtn.onclick()',renderContext);check(renderContext.__sent.some(x=>x.t==='ability'&&x.targetId==='shifter'),'ability click still targets the real selected player id');
  shapeshifted.abilityUntil=Date.now()-1;check(renderContext.__visiblePlayerName(shapeshifted)==='真实身份','expired disguise falls back to real name');shapeshifted.abilityUntil=Date.now()+30000;shapeshifted.disguiseTargetId='missing';check(renderContext.__visiblePlayerName(shapeshifted)==='真实身份','missing disguise target falls back to real name');

  console.log(`[roles] ok: ${assertions} assertions across production GameRoom handlers and extracted game.js role picker, renderer, display-name helper, vitals functions, and click handlers`);
})().catch(error=>{console.error(error);process.exitCode=1;});
